apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
  annotations:
    # backstage.io/managed-by-location: url:http://github.com/backstage/backstage/blob/master/catalog-info.yaml
    github.com/project-slug: backstage/backstage
    # backstage.io/techdocs-ref: dir:.  
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
