apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: Simple-python-library
  title: A Simple python library
  description: scaffolder v1beta3 template demo
  tags:
    - python
    - library
spec:
  owner: paython/Mphasis.org
  type: library

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - author
      properties:
        component_id:
          title: Name
          type: string
          description: Name of the library
          ui:autofocus: true
          ui:field: EntityNamePicker
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: A very simple python library
        author:
          title: Author
          type: string
          description: Author of library
        authorEmail:
          title: Author email
          type: string
          description: Email of author
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          author: ${{ parameters.author }}
          authorEmail: ${{ parameters.authorEmail }}

    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'